const products = [
  {
    id: 1,
    image: 'https://via.placeholder.com/100',
    name: 'کرم ضد آفتاب لافار',
    category: 'کرم ضد آفتاب',
    oldPrice: '۴۴۳,۰۰۰',
    newPrice: '۱۸۹,۰۰۰',
    discount: 15,
  },
  {
    id: 2,
    image: 'https://via.placeholder.com/100',
    name: 'ادوپرفیوم زنانه روونا',
    category: 'ادو پرفیوم',
    oldPrice: '۴۳۸,۰۰۰',
    newPrice: '۳۳۷,۰۰۰',
    discount: 12,
  },
  {
    id: 3,
    image: 'https://via.placeholder.com/100',
    name: 'کرم مرطوب کننده آبرسان',
    category: 'آبرسان، مرطوب کننده',
    oldPrice: '۵۰,۰۰۰',
    newPrice: '۴۲,۹۰۰',
    discount: 14,
  },
  {
    id: 4,
    image: 'https://via.placeholder.com/100',
    name: 'ماسک صورت شب بایو آکوا',
    category: 'ماسک صورت',
    oldPrice: '۳۸۹,۰۰۰',
    newPrice: '۱۸۹,۰۰۰',
    discount: 25,
  },
  {
    id: 5,
    image: 'https://via.placeholder.com/100',
    name: 'کرم ضد آفتاب لافار',
    category: 'کرم ضد آفتاب',
    oldPrice: '۴۴۳,۰۰۰',
    newPrice: '۱۸۹,۰۰۰',
    discount: 15,
  },
  {
    id: 6,
    image: 'https://via.placeholder.com/100',
    name: 'ادوپرفیوم زنانه روونا',
    category: 'ادو پرفیوم',
    oldPrice: '۴۳۸,۰۰۰',
    newPrice: '۳۳۷,۰۰۰',
    discount: 12,
  },
  {
    id: 7,
    image: 'https://via.placeholder.com/100',
    name: 'کرم مرطوب کننده آبرسان',
    category: 'آبرسان، مرطوب کننده',
    oldPrice: '۵۰,۰۰۰',
    newPrice: '۴۲,۹۰۰',
    discount: 14,
  },
  {
    id: 8,
    image: 'https://via.placeholder.com/100',
    name: 'ماسک صورت شب بایو آکوا',
    category: 'ماسک صورت',
    oldPrice: '۳۸۹,۰۰۰',
    newPrice: '۱۸۹,۰۰۰',
    discount: 25,
  },
]

export default products
